import base64
import json
from collections import deque

import cv2
import numpy as np
import mediapipe as mp
import onnxruntime as ort
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware

from dataset import normalize_sequence  # NEW: same preprocessing used in training

# --- Config ---
SEQUENCE_LENGTH = 33      # must match training (max_len from dataset.py)
NUM_FEATURES = 258        # 33*4 (pose) + 21*3 (left hand) + 21*3 (right hand)
MODEL_PATH = "signbridge_model.onnx"       # exported via export_to_onnx.py
LABEL_MAP_PATH = "label_map.json"          # generated by export_to_onnx.py
LANDMARKER_MODEL_PATH = "holistic_landmarker.task"
CONFIDENCE_THRESHOLD = 0.4                 # NEW: don't show low-confidence guesses in demo

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten this in production
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Load label map (generated fresh by export_to_onnx.py, matches current checkpoint) ---
with open(LABEL_MAP_PATH, "r") as f:
    label_map = json.load(f)  # {"0": "afternoon", "1": "animal", ...}

# --- Load ONNX model once at startup ---
ort_session = ort.InferenceSession(MODEL_PATH)

# --- MediaPipe Holistic Landmarker setup (image mode, since frames arrive one at a time) ---
BaseOptions = mp.tasks.BaseOptions
HolisticLandmarker = mp.tasks.vision.HolisticLandmarker
HolisticLandmarkerOptions = mp.tasks.vision.HolisticLandmarkerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

landmarker_options = HolisticLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=LANDMARKER_MODEL_PATH),
    running_mode=VisionRunningMode.VIDEO,
)


def landmarks_to_array(landmark_list, num_points, dims=3):
    if not landmark_list:
        return np.zeros(num_points * dims)
    arr = []
    for lm in landmark_list:
        if dims == 3:
            arr.extend([lm.x, lm.y, lm.z])
        else:
            arr.extend([lm.x, lm.y, lm.z, lm.visibility])
    return np.array(arr)


def pad_or_trim(sequence, target_len=SEQUENCE_LENGTH):
    sequence = np.array(sequence)
    length = sequence.shape[0]
    if length == target_len:
        return sequence
    if length > target_len:
        return sequence[:target_len]
    pad = np.zeros((target_len - length, sequence.shape[1]))
    return np.vstack([sequence, pad])


@app.get("/")
def health_check():
    return {"status": "SignBridge backend running", "num_classes": len(label_map)}


@app.websocket("/ws/predict")
async def predict_ws(websocket: WebSocket):
    await websocket.accept()
    frame_buffer = deque(maxlen=SEQUENCE_LENGTH)
    frame_idx = 0

    landmarker = HolisticLandmarker.create_from_options(landmarker_options)

    try:
        while True:
            message = await websocket.receive_text()
            data = json.loads(message)

            if data.get("type") == "frame":
                # Decode base64 image sent from the browser
                img_b64 = data["image"].split(",")[-1]  # strip "data:image/jpeg;base64," prefix if present
                img_bytes = base64.b64decode(img_b64)
                img_array = np.frombuffer(img_bytes, dtype=np.uint8)
                frame = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

                if frame is None:
                    continue

                rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb_frame)
                timestamp_ms = frame_idx * 33  # approx 30fps
                frame_idx += 1

                result = landmarker.detect_for_video(mp_image, timestamp_ms)

                pose = landmarks_to_array(result.pose_landmarks, 33, dims=4)
                lh = landmarks_to_array(result.left_hand_landmarks, 21, dims=3)
                rh = landmarks_to_array(result.right_hand_landmarks, 21, dims=3)
                frame_landmarks = np.concatenate([pose, lh, rh])

                frame_buffer.append(frame_landmarks)

                # Once we have a full sequence, run prediction
                if len(frame_buffer) == SEQUENCE_LENGTH:
                    sequence = pad_or_trim(list(frame_buffer))

                    # NEW: apply the EXACT same normalization used in training
                    # (shoulder-centered, shoulder-width-scaled). Without this,
                    # live predictions don't match what the model learned on.
                    sequence = normalize_sequence(sequence)

                    onnx_input = sequence.reshape(1, SEQUENCE_LENGTH, NUM_FEATURES).astype(np.float32)

                    outputs = ort_session.run(None, {"landmark_sequence": onnx_input})[0]
                    probs = np.exp(outputs) / np.sum(np.exp(outputs), axis=1, keepdims=True)  # softmax
                    pred_idx = int(np.argmax(probs, axis=1)[0])
                    confidence = float(probs[0][pred_idx])
                    predicted_sign = label_map[str(pred_idx)]

                    # NEW: suppress low-confidence noise in the demo
                    if confidence >= CONFIDENCE_THRESHOLD:
                        await websocket.send_json({
                            "type": "prediction",
                            "sign": predicted_sign,
                            "confidence": round(confidence, 3)
                        })
                    else:
                        await websocket.send_json({
                            "type": "prediction",
                            "sign": "...",
                            "confidence": round(confidence, 3)
                        })

            elif data.get("type") == "reset":
                frame_buffer.clear()
                frame_idx = 0

    except WebSocketDisconnect:
        print("Client disconnected")
    finally:
        landmarker.close()